<?php
DEFINE("DATABASE_URL",'localhost');
DEFINE("DATABASE_NAME",  'driedmeats');
DEFINE("DATABASE_USER_NAME",  "root");
DEFINE("DATABASE_PASSWORD",  "");

//DEFINE("DATABASE_URL",'localhost');
//DEFINE("DATABASE_NAME",  'zavm07');
//DEFINE("DATABASE_USER_NAME",  "zavm07");
//DEFINE("DATABASE_PASSWORD",  "Mie7EiKunaicoChai3");
?>